name: "build-test-dev"
on:
  pull_request:
    branches:
      - dev
    paths-ignore:
      - '*.md'
  push:
    branches:
      - master
      - main
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild (vswhere-path)
      id: setup_msbuild_explicit
      uses: ./
      with:
        vswhere-path: C:\ProgramData\chocolatey\bin

    - name: Setup MSBuild (PATH)
      id: setup_msbuild_path
      uses: ./

    - name: Setup MSBuild (fallback)
      id: setup_msbuild_fallback
      uses: ./
      env:
        PATH: ''

    - name: Setup MSBuild (x64)
      id: setup_msbuild_path
      uses: ./
      with:
        vs-prerelease: true
        msbuild-architecture: 'x64'

    - name: echo msbuild path
      run: |
        echo "vswhere-path: ${{ steps.setup_msbuild_explicit.outputs.msbuildPath }}"
        echo "PATH: ${{ steps.setup_msbuild_path.outputs.msbuildPath }}"
        echo "Fallback: ${{ steps.setup_msbuild_fallback.outputs.msbuildPath }}"

    - name: echo MSBuild
      run: msbuild -version
